# Generated by Django 3.2.7 on 2021-09-26 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Judul Proposal.', max_length=512)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('judul_submitted', 'Submit judul'), ('judul_approved', 'Judul approved'), ('proposal_submitted', 'Submit proposal'), ('proposal_revised', 'Submit revisi proposal'), ('proposal_dosen_ok', 'Proposal disetujui dosen pembimbing'), ('proposal_kaprodi_ok', 'Proposal disetujui kaprodi'), ('proposal_dosen_no', 'Proposal tidak disetujui dosen pembimbing'), ('proposal_kaprodi_no', 'Proposal tidak disetujui kaprodi'), ('proposal_approved', 'Proposal approved')], default='judul_submitted', help_text='Status', max_length=100)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.proposal')),
            ],
        ),
    ]
