# Generated by Django 3.2.7 on 2021-09-26 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('judul_submitted', 'Submit judul'), ('judul_approved', 'Judul approved'), ('proposal_submitted', 'Submit proposal'), ('proposal_revised', 'Submit revisi proposal'), ('proposal_dosen_ok', 'Proposal disetujui dosen pembimbing'), ('proposal_kaprodi_ok', 'Proposal disetujui kaprodi'), ('proposal_dosen_no', 'Proposal tidak disetujui dosen pembimbing'), ('proposal_kaprodi_no', 'Proposal tidak disetujui kaprodi'), ('proposal_approved', 'Proposal approved')], help_text='Status', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
